options:
  debug:
    default: !!bool false
    type: boolean
    description: Enable debug logging
  verbose:
    default: !!bool false
    type: boolean
    description: Enable verbose logging
  use-syslog:
    type: boolean
    default: !!bool false
    description: |
      Setting this to True will allow supporting services to log to syslog.
  use-internal-endpoints:
    type: boolean
    default: !!bool false
    description: |
      Openstack mostly defaults to using public endpoints for
      internal communication between services. If set to True this option
      will configure services to use internal endpoints where possible.
  san-ip:
    type: string
    description: "Management VIP address of the Pure Storage FlashArray"
    default: !!null ""
  san-login:
    type: string
    description: "Unisphere username"
    default: !!null ""
  san-password:
    type: string
    description: "Unisphere password"
    default: !!null ""
  hpmsa_backend_name:
    type: string
    description: |
      A storage backend name to be used.
      This option is required.
    default: !!null ""
  volume_backend_name:
    type: string
    description: |
      A storage backend name to be used.
      This option is required.
    default: !!null ""
  hpmsa_pool_name:
    type: string
    description: |
      A storage pool name to be used.
      This option is required.
    default: !!null ""
  hpmsa_iscsi_ips:
    type: string
    description:  |
      A space-delimited list of iSCSI ips to be used.
      See: https://docs.openstack.org/cinder/xena/configuration/block-storage/drivers/hp-msa-driver.html
      for details on how should the isci ip be presented.
      This option is required
    default: !!null ""
  driver_use_ssl:
    type: boolean
    default: !!bool True
    description: |
      Should be set to true to enable use of the HTTPS protocol.
  hpmsa_verify_certificate:
    type: boolean
    default: !!bool False
    description: |
      Should be set to false to disable verification of certificates.